version: '3.7'
services:
  demo_db:
    container_name: demo-mysql-db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha1234
      MYSQL_DATABASE: bancodedados2
  demo_dbPostgress:
    container_name: demo_dbPostgress
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha1234
      POSTGRES_USER: usuario
      POSTGRES_DB: postgres
  demo_mongodb:
    container_name: demo_mongodb
    image:  mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha1234
      MONGO_INITDB_DATABASE: bancodedados
    #mongo-express:
    #image: mongo-express
    #restart: always
    #ports:
    #  - 8081:8081
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    #  ME_CONFIG_BASICAUTH: false